# Generated by Django 6.0.2 on 2026-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='customer',
            new_name='costumer',
        ),
    ]
