# Generated by Django 6.0.2 on 2026-03-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='costumer',
            new_name='customer',
        ),
    ]
