# Generated by Django 6.0.2 on 2026-02-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmanager', '0002_rename_customer_asset_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netmanager.costumer'),
        ),
    ]
