# Generated by Django 6.0.2 on 2026-02-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmanager', '0004_alter_asset_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
    ]
